name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
template: |
  ## Changes

  $CHANGES

categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
  - title: '🧰 Maintenance'
    label: 'chore'
  - title: '📖 Documentation'
    label:
      - 'docs'
      - 'documentation'
  - title: '🆙 Dependency Updates'
    label: 'deps'

version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
  minor:
    labels:
      - 'minor'
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'patch'
      - 'bug'
      - 'chore'
      - 'documentation'
      - 'docs'
      - 'deps'
  default: patch

exclude-labels:
  - 'skip-changelog'

autolabeler:
  - label: 'documentation'
    files:
      - '*.md'
    branch:
      - '/docs{0,1}\/.+/'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
    title:
      - '/fix/i'
    body:
      - '/Fixes:\s#[0-9]{1,4}/'
  - label: 'enhancement'
    branch:
      - '/feature\/.+/'
    titile:
      - '/feat/i'
