name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          # Or Use `.npmrc` instead of `node-version`
          # node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install dependencies & Build
        run: |
          corepack enable
          pnpm install
          pnpm run --if-present build

      - name: Run tests
        run: pnpm run --if-present test
