name: PR Comment Trigger

on:
  issue_comment:
    types: [created]

jobs:
  pr_commented:
    runs-on: ubuntu-latest
    steps:
      - uses: yuler/pr-comment-trigger@main
        id: 'pr'
        with:
          trigger: '/trigger'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - name: Wait 2 seconds # sleep 2s wait for cancel
        run: sleep 2
      - uses: actions/checkout@v2
        with:
          ref: ${{ steps.pr.outputs.branch }}
      - name: Echo
        run: Echo Trigger
