name: PR Comment Trigger

on:
  issue_comment:
    types: [created]

jobs:
  pr_commented:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: yuler/pr-comment-trigger@main
        id: 'pr'
        with:
          trigger: '/trigger'
      - name: echo
        if: ${{ steps.pr.outputs.triggered }} # condition for skip
        run: |
          echo "${{ steps.pr.outputs.triggered }}"
